<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Core\TheCanonry.Schema\TheCanonry.Schema.csproj" />
    <ProjectReference Include="..\Core\TheCanonry.Engine\TheCanonry.Engine.csproj" />
    <ProjectReference Include="..\Infrastructure\TheCanonry.ApiClients\TheCanonry.ApiClients.csproj" />
    <ProjectReference Include="..\Infrastructure\TheCanonry.Persistence\TheCanonry.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
