#!/usr/bin/env bash
set -euo pipefail

# Migration Delta Checker
# Compares the TS web app navigation structure against the C# desktop app
# to report which views/tabs are missing from the desktop.
#
# Usage: ./scripts/migration-delta.sh [path-to-ts-repo]
#
# The TS repo defaults to ../the-canonry (sibling directory).

TS_REPO="${1:-$(cd "$(dirname "$0")/../../the-canonry" 2>/dev/null && pwd || echo "")}"
CS_REPO="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="$CS_REPO/docs/migration-manifest.json"

if [[ -z "$TS_REPO" || ! -d "$TS_REPO/apps" ]]; then
  echo "ERROR: Cannot find TS repo. Pass path as argument or place it at ../the-canonry"
  exit 1
fi

echo "TS repo: $TS_REPO"
echo "CS repo: $CS_REPO"
echo ""

# ─── Extract TS navigation structure ────────────────────────────────────────

echo "Extracting TS navigation..."

# Top-level modules from Canonry shell Navigation.jsx
TS_MODULES=$(grep -oP '\{ id: "\K[^"]+' "$TS_REPO/apps/canonry/webui/src/components/Navigation.jsx" 2>/dev/null || true)

# Per-module tabs from each *Remote.tsx/jsx TABS constant
declare -A TS_TABS
for remote in "$TS_REPO"/apps/*/webui/src/*Remote.{tsx,jsx}; do
  [[ -f "$remote" ]] || continue
  module_dir=$(basename "$(dirname "$(dirname "$(dirname "$remote")")")")
  # Extract tab IDs from the TABS array (lines like { id: "foo", label: "Bar" })
  tabs=$(sed -n '/^const TABS/,/^];/p' "$remote" | grep -oP 'id: "\K[^"]+' || true)
  if [[ -n "$tabs" ]]; then
    TS_TABS["$module_dir"]="$tabs"
  fi
done

# Illuminator sidebar groups (separate extraction since it's not in a Remote file)
ILLUM_SIDEBAR="$TS_REPO/apps/illuminator/webui/src/components/IlluminatorSidebar.jsx"
if [[ -f "$ILLUM_SIDEBAR" ]]; then
  # Filter out group-level IDs, keep tab-level IDs
  illum_tabs=$(sed -n '/tabs:/,/]/{ /id:/p }' "$ILLUM_SIDEBAR" | grep -oP 'id: "\K[^"]+')
  TS_TABS["illuminator-sidebar"]="$illum_tabs"
fi

# ─── Extract CS desktop structure ───────────────────────────────────────────

echo "Extracting CS desktop navigation..."

# ViewModels registered in App.axaml.cs
CS_VIEWMODELS=$(grep -oP 'AddTransient<\K[^>]+' "$CS_REPO/src/TheCanonry.Desktop/App.axaml.cs" 2>/dev/null || true)

# Navigation registrations (name + VM type)
CS_NAV_ITEMS=$(grep -oP 'RegisterView<[^>]+>\("([^"]+)"' "$CS_REPO/src/TheCanonry.Desktop/App.axaml.cs" 2>/dev/null | \
  sed 's/RegisterView<\([^>]*\)>("\([^"]*\)"/\2 → \1/' || true)

# All View files (*.axaml UserControls)
CS_VIEWS=$(find "$CS_REPO/src/TheCanonry.Desktop" -name "*.axaml" ! -name "App.axaml" ! -name "ShellWindow.axaml" -printf "%P\n" 2>/dev/null | sort || true)

# ─── Build manifest ─────────────────────────────────────────────────────────

echo "Building manifest..."
mkdir -p "$(dirname "$MANIFEST")"

# Start JSON
cat > "$MANIFEST" << 'HEADER'
{
  "generated": "TIMESTAMP",
  "description": "Migration delta between TS web app and C# desktop app. Generated by scripts/migration-delta.sh",
  "ts_repo": "TS_REPO_PATH",
  "modules": {
HEADER

sed -i "s|TIMESTAMP|$(date -Iseconds)|" "$MANIFEST"
sed -i "s|TS_REPO_PATH|$TS_REPO|" "$MANIFEST"

first_module=true

for module in $TS_MODULES; do
  if [[ "$first_module" == "false" ]]; then
    echo "," >> "$MANIFEST"
  fi
  first_module=false

  # Map TS module ID to its display label
  case "$module" in
    enumerist) label="Enumerist (Schema Editor)" ;;
    names) label="Name Forge" ;;
    cosmography) label="Cosmographer" ;;
    coherence) label="Coherence Engine" ;;
    simulation) label="Lore Weave" ;;
    illuminator) label="Illuminator" ;;
    archivist) label="Archivist" ;;
    chronicler) label="Chronicler" ;;
    *) label="$module" ;;
  esac

  # Map TS module ID to the directory name used in TS_TABS
  case "$module" in
    names) tab_key="name-forge" ;;
    cosmography) tab_key="cosmographer" ;;
    coherence) tab_key="coherence-engine" ;;
    simulation) tab_key="lore-weave" ;;
    *) tab_key="$module" ;;
  esac

  # Check if a corresponding CS ViewModel exists
  case "$module" in
    enumerist) cs_vm="DomainEditorViewModel" ;;
    names) cs_vm="" ;;
    cosmography) cs_vm="" ;;
    coherence) cs_vm="" ;;
    simulation) cs_vm="LoreWeaveViewModel" ;;
    illuminator) cs_vm="IlluminatorViewModel" ;;
    archivist) cs_vm="ArchivistViewModel" ;;
    chronicler) cs_vm="" ;;
    *) cs_vm="" ;;
  esac

  if [[ -n "$cs_vm" ]] && echo "$CS_VIEWMODELS" | grep -q "$cs_vm"; then
    has_vm="true"
  else
    has_vm="false"
  fi

  printf '    "%s": {\n      "label": "%s",\n      "desktop_has_module": %s,\n      "desktop_viewmodel": "%s",\n      "tabs": {' \
    "$module" "$label" "$has_vm" "$cs_vm" >> "$MANIFEST"

  # Get tabs for this module
  tabs="${TS_TABS[$tab_key]:-}"

  # For illuminator, use the sidebar tabs instead
  if [[ "$module" == "illuminator" ]]; then
    tabs="${TS_TABS[illuminator-sidebar]:-}"
  fi

  first_tab=true
  if [[ -n "$tabs" ]]; then
    while IFS= read -r tab_id; do
      [[ -z "$tab_id" ]] && continue
      if [[ "$first_tab" == "false" ]]; then
        echo "," >> "$MANIFEST"
      fi
      first_tab=false

      # Check if the desktop has a matching view for this tab
      # This is a heuristic match based on known mappings
      desktop_status="missing"
      desktop_vm=""
      case "${module}:${tab_id}" in
        illuminator:entities) desktop_status="present"; desktop_vm="EntityBrowserViewModel" ;;
        illuminator:chronicle) desktop_status="present"; desktop_vm="ChronicleViewModel" ;;
        illuminator:activity) desktop_status="present"; desktop_vm="IlluminatorViewModel" ;;
        illuminator:coverage) desktop_status="present"; desktop_vm="CatalogViewModel" ;;
        illuminator:catalog) desktop_status="present"; desktop_vm="CatalogViewModel" ;;
        illuminator:curation) desktop_status="missing"; desktop_vm="" ;;
        illuminator:entitycuration) desktop_status="partial"; desktop_vm="ImageCurationViewModel" ;;
        simulation:run) desktop_status="present"; desktop_vm="LoreWeaveViewModel" ;;
        *) desktop_status="missing"; desktop_vm="" ;;
      esac

      printf '\n        "%s": { "status": "%s", "desktop_viewmodel": "%s" }' \
        "$tab_id" "$desktop_status" "$desktop_vm" >> "$MANIFEST"
    done <<< "$tabs"
  fi

  printf '\n      }\n    }' >> "$MANIFEST"
done

# Close JSON
cat >> "$MANIFEST" << 'FOOTER'

  },
  "desktop_extra_views": {
    "ChronicleWizardViewModel": "No direct TS equivalent (wizard is inline in Chronicle tab)",
    "EditionComparisonViewModel": "No direct TS equivalent (historian notes shown inline)",
    "AwsSyncViewModel": "Matches TS AWS Sync button in Navigation header",
    "DomainEditorViewModel": "Partial match for Enumerist module"
  },
  "summary": {}
}
FOOTER

# ─── Compute summary stats ──────────────────────────────────────────────────

total_modules=$(echo "$TS_MODULES" | wc -w)
present_modules=$(grep -c '"desktop_has_module": true' "$MANIFEST" || true)
missing_modules=$((total_modules - present_modules))

total_tabs=$(grep -c '"status":' "$MANIFEST" || true)
present_tabs=$(grep -c '"status": "present"' "$MANIFEST" || true)
partial_tabs=$(grep -c '"status": "partial"' "$MANIFEST" || true)
missing_tabs=$(grep -c '"status": "missing"' "$MANIFEST" || true)

# Patch summary into manifest
python3 -c "
import json, sys
with open('$MANIFEST') as f:
    data = json.load(f)
data['summary'] = {
    'total_modules': $total_modules,
    'present_modules': $present_modules,
    'missing_modules': $missing_modules,
    'total_tabs': $total_tabs,
    'present_tabs': $present_tabs,
    'partial_tabs': $partial_tabs,
    'missing_tabs': $missing_tabs,
    'completion_pct': round(($present_tabs + $partial_tabs * 0.5) / max($total_tabs, 1) * 100, 1)
}
with open('$MANIFEST', 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
" 2>/dev/null

# ─── Print report ───────────────────────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  MIGRATION DELTA REPORT"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Modules:  $present_modules / $total_modules present ($missing_modules missing)"
echo "Tabs:     $present_tabs present, $partial_tabs partial, $missing_tabs missing (of $total_tabs total)"
echo "Progress: $(python3 -c "print(round(($present_tabs + $partial_tabs * 0.5) / max($total_tabs, 1) * 100, 1))" 2>/dev/null || echo "?")%"
echo ""

echo "MISSING MODULES:"
for module in $TS_MODULES; do
  case "$module" in
    enumerist) cs_vm="DomainEditorViewModel" ;;
    simulation) cs_vm="LoreWeaveViewModel" ;;
    illuminator) cs_vm="IlluminatorViewModel" ;;
    archivist) cs_vm="ArchivistViewModel" ;;
    *) cs_vm="" ;;
  esac
  if [[ -z "$cs_vm" ]] || ! echo "$CS_VIEWMODELS" | grep -q "$cs_vm"; then
    echo "  ✗ $module"
  fi
done
echo ""

echo "MISSING/PARTIAL TABS:"
# Parse the manifest for missing tabs
python3 -c "
import json
with open('$MANIFEST') as f:
    data = json.load(f)
for mod_id, mod in data['modules'].items():
    missing = []
    for tab_id, tab in mod['tabs'].items():
        if tab['status'] != 'present':
            missing.append((tab_id, tab['status']))
    if missing:
        print(f'  {mod[\"label\"]}:')
        for tab_id, status in missing:
            marker = '◐' if status == 'partial' else '✗'
            print(f'    {marker} {tab_id}')
" 2>/dev/null

echo ""
echo "Manifest written to: $MANIFEST"
echo "Re-run this script at any time to check progress."
